### ISSUE TITLE
Kummerkasten

### ISSUE THREAD

**Issue by d0mmi** [project-redhead/redhead#10]
- [x] Database
- [x] Bean
- [x] Json
- [x] Discord Webhook als Notification mit link zur Website

**Comment by ginomessmer** [comment]
Vorschlag

## Einsendungen
Ich würde was das Front End betrifft die Einsendungen als JSON per AJAX senden, da es nur ein kleines Feature ist.

Das Payload würde etwa nur so aussehen:

```json
{
  "content": "Messgeräte"
}
```

In der Datenbank könnten wir folgende Properties haben:

|Key|Type|Value|Default|
|---|---|---|---|
|_id|Object ID||N/A|
|userId|string|Entzogen aus dem JWT Cookie (=> `HttpUtils.getUserIdFromJwt()`)|N/A|
|content|string|_content_|N/A|
|status|enum (string?)|`unread` oder `read`|`unread`|
|submittedAt|DateTime||_current date time_|


## Liste
Dazu würde ich innerhalb der JSP eine Bean abfragen, die alle meine Einsendungen zurückliefert. Dazu können wir alle Properties aus dem Datenbankschema nehmen.

---

@d0mmi Nur mein spontaner Einfall. Gib mir Bescheid, was du davon hältst.

**Comment by d0mmi** [comment]
hört sich gut an würde aber den status als boolean speichern
